name: Build CentOS 7.9 binary

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., v1.2.3)'
        required: false
        type: string
  push:
    tags:
      - 'v*'

jobs:
  build-centos7:
    name: Build binary for CentOS 7.9
    # 使用 ubuntu-latest 是因为我们需要较新的 GitHub Actions 运行环境
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.version || github.ref }}

    # 使用 quay.io/centos/centos:7 作为构建环境，这保证了我们使用 CentOS 7 的系统库
    - name: Build in CentOS 7 Docker
      run: |
        # 创建构建脚本
        cat > build.sh << 'EOL'
        #!/bin/bash
        set -e

        # 安装构建所需工具
        yum group install -y "Development Tools"
        yum install -y curl centos-release-scl
        yum install -y devtoolset-9

        # 安装 Rust
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.79.0
        source $HOME/.cargo/env

        # 启用 devtoolset-9 获取较新的编译器，但仍然使用系统的 glibc
        source /opt/rh/devtoolset-9/enable

        # 构建
        cd /work
        cargo build --release --locked --target x86_64-unknown-linux-gnu

        # 确保构建产物属于 runner 用户
        chown -R 1001:1001 target/
        EOL

        # 设置脚本权限
        chmod +x build.sh

        # 在 CentOS 7 容器中运行构建
        docker run --rm \
          -v $(pwd):/work \
          -w /work \
          quay.io/centos/centos:7 \
          ./build.sh

    - name: Check binary compatibility
      run: |
        # 检查二进制文件的 glibc 依赖
        echo "Checking glibc requirements:"
        ldd target/x86_64-unknown-linux-gnu/release/meilisearch || true
        echo "Checking symbol versions:"
        readelf -V target/x86_64-unknown-linux-gnu/release/meilisearch || true
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: meilisearch-linux-centos7-amd64
        path: target/x86_64-unknown-linux-gnu/release/meilisearch
        if-no-files-found: error